Update requirements.txt
update test dependencies, got a conflict:

ERROR: Cannot install -r requirements.txt (line 12) and pytest==5.4.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pytest==5.4.2
    pytest-asyncio 0.18.2 depends on pytest>=6.1.0